//  MACROS  //

#undef SABRE_XX_FIELDS_HEADER
#undef SABRE_XX_FIELDS_DEFINE
#undef SABRE_XX_FIELDS_DESCRIBE
#undef SABRE_XX_FIELDS_TYPEDEF
#undef SABRE_XX_FIELDS_FOOTER
#undef SABRE_XX_STATICS_HEADER
#undef SABRE_XX_STATICS_DEFINE
#undef SABRE_XX_STATICS_DESCRIBE
#undef SABRE_XX_STATICS_TYPEDEF
#undef SABRE_XX_STATICS_FOOTER
