name: Build Runtime
description: Workflow for building Sabre artifacts

on:
    workflow_call:
        inputs:
            release:
                type: string
                required: false
                default: canary
                description: Release Type

jobs:
    target-build:
        runs-on: ${{ matrix.host }}
        name: Target '${{ matrix.label }}-${{ matrix.arch }}'

        strategy:
            fail-fast: true
            matrix:
                include:
                    - { label: darwin, arch: x64, host: macos-latest }
                    - { label: darwin, arch: arm64, host: macos-latest }
                    - { label: linux, arch: x64, host: ubuntu-latest }
                    - { label: linux, arch: arm64, host: ubuntu-24.04-arm }
                    - { label: windows, arch: x64, host: windows-latest }
                    # # excluding windows-arm for now until ready for development
                    # # - { label: windows, arch: arm64, host: windows-11-arm }

        steps:
            - uses: actions/checkout@v6
            - uses: lukka/get-cmake@latest

            - uses: ZhongRuoyu/setup-llvm@v0
              with: { llvm-version: 22 }

            - name: Building '${{ matrix.label }}-${{ matrix.arch }}'
              run: ${{ github.workspace }}/scripts/compile/target.${{ runner.os == 'Windows' && 'ps1' || 'sh' }} ${{ matrix.label }} ${{ matrix.arch }} build ${{ inputs.release }}

            - name: Testing '${{ matrix.label }}-${{ matrix.arch }}'
              timeout-minutes: 1 # should never go longer than this
              run: |
                  ${{ github.workspace }}/dist/bin/sabre --revision
                  ${{ github.workspace }}/dist/bin/sabre test

            - name: Compress Artifacts
              uses: thedoctor0/zip-release@0.7.5
              with:
                  type: zip
                  directory: dist
                  filename: ../sabre-${{ matrix.label }}-${{ matrix.arch }}.zip

            - name: Upload Artifacts
              uses: actions/upload-artifact@v7
              with:
                  overwrite: true
                  name: sabre-${{ matrix.label }}-${{ matrix.arch }}
                  path: sabre-${{ matrix.label }}-${{ matrix.arch }}.zip
