name: Release Canary
description: Workflow for publishing Sabre canary releases
on: [workflow_dispatch]

jobs:
    canary-release:
        name: Canary Dispatch
        with: { release: canary }
        uses: ./.github/workflows/release.yml
