name: Publish Release
description: Workflow for publishing Sabre releases to GitHub

on:
    workflow_call:
        inputs:
            release:
                type: string
                required: true
                description: Release Type

jobs:
    publish-release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Parse Release Version
              id: version
              run: |
                  VERSION_SUFFIX=${{ inputs.release != 'stable' && format('-{0}', inputs.release) || '' }}
                  VERSION_SEMANTIC=$(cat ${{ github.workspace }}/configs/version.txt | xargs)
                  echo "short=v$VERSION_SEMANTIC$VERSION_SUFFIX" >> $GITHUB_OUTPUT
                  echo "long=v$VERSION_SEMANTIC-${{ inputs.release }}" >> $GITHUB_OUTPUT

            - name: Generate Changelog
              uses: elieahd/templater@v1
              with:
                  file: "CHANGELOG.md"
                  variables: "version=${{ steps.version.outputs.short }}"
                  template: ".github/templates/release-${{ inputs.release }}.md"

            - name: Download Artifacts
              uses: actions/download-artifact@v8
              with:
                  path: dist
                  pattern: sabre-*
                  merge-multiple: true

            - name: Deduplicate Canary
              if: inputs.release == 'canary'
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERSION_TAG: ${{ steps.version.outputs.long }}
              run: |
                  if gh release view "$VERSION_TAG" &>/dev/null; then
                      gh release delete "$VERSION_TAG" --cleanup-tag --yes
                  fi

            - name: Generate Release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release create ${{ steps.version.outputs.long }} "./dist/*" \
                    --title "Sabre ${{ steps.version.outputs.long }}" \
                    --notes-file "CHANGELOG.md" \
                    --repo "${{ github.repository }}" \
                    --latest=${{ inputs.release == 'stable' && 'true' || 'false' }}

            - name: Update Canary
              if: inputs.release == 'canary'
              run: gh release edit $VERSION_TAG --prerelease
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERSION_TAG: ${{ steps.version.outputs.long }}
