name: Release Worker
description: Workflow for publishing a Sabre release

on:
    workflow_call:
        inputs:
            release:
                type: string
                required: false
                default: canary
                description: Release Type

jobs:
    release-build:
        name: Build Release
        uses: ./.github/workflows/builder.yml
        with:
            release: ${{ inputs.release }}

    release-vscode:
        name: Publish VSCE
        secrets: inherit
        needs: [release-build]
        if: inputs.release == 'stable'
        uses: ./.github/workflows/vscode.yml

    release-website:
        name: Publish Website
        needs: [release-build]
        if: inputs.release == 'stable'
        uses: ./.github/workflows/website.yml

    release-publish:
        name: Publish Release
        needs: [release-build]
        uses: ./.github/workflows/publish.yml
        with:
            release: ${{ inputs.release }}
