name: Publish VSCE
description: Workflow for publishing the Sabre VSC extension
on: [workflow_dispatch, workflow_call]

jobs:
    vscode-publish:
        name: VSCE Dispatch
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: oven-sh/setup-bun@v2

            - name: Install Dependencies
              run: bun install

            - name: Build Extension
              run: bun vscode bundle

            - name: Package Extension
              run: bunx vsce package --no-dependencies
              working-directory: dist/vscode

            - name: Publish Extension
              continue-on-error: true
              working-directory: dist/vscode
              run: bunx vsce publish -p ${{ secrets.VSCODE_EXTENSION_TOKEN }}
